### ISSUE TITLE
ft2 error after including libs in properties

### ISSUE THREAD

**Issue by HadenGrenade** [Lexiyx/LegendWare-ReWork#1]
i already included everything but for some reason it still says it cant find <ft2build.h>

**Comment by Lexiyx** [comment]
It depends on the build you choose. So you need to set it separately for Release and Debug. If the problem persists despite this, you can check the following sites;

https://techoverflow.net/2019/06/11/how-to-fix-ft2build-h-no-such-file-or-directory/
https://stackoverflow.com/questions/12490015/visual-studio-cant-see-my-included-header-files
https://stackoverflow.com/questions/39107730/ft2build-h-no-such-file-or-directory-freetype-2-6

Can you also send your problem as an image because the solutions vary according to what it writes there.

**Comment by HadenGrenade** [comment]
![image](https://user-images.githubusercontent.com/80079690/220767153-79806dda-08d2-415e-bc39-7d249a066345.png)
basically the same thing for the library directories, and yes it is the correct architecture.
tried all of those nothing really worked

**Comment by Lexiyx** [comment]
Strange I have never encountered such a problem before. I dont think it will be relevant if you have a Visual Studio update, but it is worth trying. Would you also try to run it as an administrator? Your FreeType may be corrupted maybe you can try downloading it again?

**Comment by Lexiyx** [comment]
Also do you have such problems in other projects?

**Comment by Lexiyx** [comment]
Im going to send you a cheat that is LegendWare Paste again recently but the menu has been updated can you look at it to see if the same problems persist?

**Comment by HadenGrenade** [comment]
1. No vs update & running as admin makes no difference. 
2. i tried redownloading but that didnt do anything 
3. no other projects experience this issue it's very odd
4. sounds good im happy to see!

**Comment by Lexiyx** [comment]
Im sorry again for responding late. I shared a new project and I gave the FreeType.lib file I used in the Issue section can you try it on that project I just threw?
